# Generated by Django 6.0.1 on 2026-01-10 17:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_flashsalesession_flashsaleitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique voucher code (case-insensitive)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Voucher name for display", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Voucher description/terms"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED_AMOUNT", "Fixed Amount"),
                        ],
                        default="PERCENTAGE",
                        help_text="Type of discount",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Discount value (percentage or fixed amount in VND)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Maximum discount amount (for percentage discounts)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_spend",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Minimum order value to apply voucher",
                        max_digits=12,
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of times this voucher can be used (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum times a single user can use this voucher",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this voucher has been used",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Voucher start date/time"),
                ),
                ("end_date", models.DateTimeField(help_text="Voucher end date/time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("EXPIRED", "Expired"),
                            ("USED_UP", "Used Up"),
                        ],
                        default="ACTIVE",
                        help_text="Voucher status",
                        max_length=20,
                    ),
                ),
                (
                    "first_order_only",
                    models.BooleanField(
                        default=False, help_text="Only applicable for first-time orders"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categories this voucher applies to (empty = all categories)",
                        related_name="vouchers",
                        to="products.category",
                    ),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific products this voucher applies to (empty = all products)",
                        related_name="vouchers",
                        to="products.product",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher",
                "verbose_name_plural": "Vouchers",
                "db_table": "vouchers_voucher",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLAIMED", "Claimed"),
                            ("USED", "Used"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="CLAIMED",
                        max_length=20,
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times user has used this voucher",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="Last usage timestamp", null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Discount amount applied",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Order ID where voucher was used",
                        null=True,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_vouchers",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Voucher",
                "verbose_name_plural": "User Vouchers",
                "db_table": "vouchers_user_voucher",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["code"], name="vouchers_vo_code_7a7b6a_idx"),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["status"], name="vouchers_vo_status_06506c_idx"),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["start_date", "end_date"], name="vouchers_vo_start_d_ab7daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uservoucher",
            index=models.Index(
                fields=["user", "status"], name="vouchers_us_user_id_dcb7c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uservoucher",
            index=models.Index(
                fields=["voucher", "status"], name="vouchers_us_voucher_eafba3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uservoucher",
            unique_together={("user", "voucher")},
        ),
    ]
