# Generated by Django 6.0.1 on 2026-01-10 15:22

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Manufacturer name", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Manufacturer description"),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True,
                        help_text="URL to manufacturer logo",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Manufacturer website", null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country of origin", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this manufacturer active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "db_table": "products_manufacturer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="URL to category image",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this category active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Parent category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "products_category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=300)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name", max_length=300, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Product description"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Short product description",
                        max_length=500,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Regular price in VND",
                        max_digits=12,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Sale price in VND",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("MEDICINE", "Medicine"),
                            ("SUPPLEMENT", "Supplement"),
                            ("MEDICAL_DEVICE", "Medical Device"),
                            ("COSMETIC", "Cosmetic"),
                            ("OTHER", "Other"),
                        ],
                        default="MEDICINE",
                        help_text="Type of product",
                        max_length=20,
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(
                        blank=True, help_text="Product ingredients/composition"
                    ),
                ),
                (
                    "dosage",
                    models.TextField(blank=True, help_text="Dosage instructions"),
                ),
                ("usage", models.TextField(blank=True, help_text="Usage instructions")),
                (
                    "contraindications",
                    models.TextField(
                        blank=True, help_text="Contraindications and warnings"
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Possible side effects"),
                ),
                (
                    "storage",
                    models.TextField(blank=True, help_text="Storage instructions"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="Hộp",
                        help_text="Unit of measurement (Hộp, Vỉ, Chai, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.CharField(
                        blank=True,
                        help_text="Quantity per unit (e.g., '10 viên/vỉ, 3 vỉ/hộp')",
                        max_length=100,
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Current stock quantity"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=10, help_text="Low stock warning threshold"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                        ],
                        default="DRAFT",
                        help_text="Product status",
                        max_length=20,
                    ),
                ),
                (
                    "requires_prescription",
                    models.BooleanField(
                        default=False, help_text="Requires prescription to purchase"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Featured product"),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, help_text="SEO title", max_length=200),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, help_text="SEO description", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        help_text="Product manufacturer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products_product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        help_text="URL to image in storage", max_length=500
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=200,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary/featured image?"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Associated product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "products_product_image",
                "ordering": ["sort_order", "-is_primary"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="products_pr_status_041708_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer"], name="products_pr_manufac_76825d_idx"
            ),
        ),
    ]
