# Generated by Django 6.0.1 on 2026-01-10 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashSaleSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Flash sale session name", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Session description"),
                ),
                (
                    "banner_image",
                    models.CharField(
                        blank=True,
                        help_text="Banner image URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Flash sale start time")),
                ("end_time", models.DateTimeField(help_text="Flash sale end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("ENDED", "Ended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        help_text="Session status",
                        max_length=20,
                    ),
                ),
                (
                    "max_items_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum items a user can buy per product in this session",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this session active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flash_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flash Sale Session",
                "verbose_name_plural": "Flash Sale Sessions",
                "db_table": "products_flash_sale_session",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="FlashSaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Original price (snapshot at creation)",
                        max_digits=12,
                    ),
                ),
                (
                    "flash_sale_price",
                    models.DecimalField(
                        decimal_places=0, help_text="Flash sale price", max_digits=12
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        help_text="Total quantity available for flash sale"
                    ),
                ),
                (
                    "remaining_quantity",
                    models.PositiveIntegerField(help_text="Remaining quantity"),
                ),
                (
                    "sold_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of items sold"
                    ),
                ),
                (
                    "max_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum quantity per user (overrides session setting)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this item active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product in flash sale",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_sale_items",
                        to="products.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Flash sale session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.flashsalesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flash Sale Item",
                "verbose_name_plural": "Flash Sale Items",
                "db_table": "products_flash_sale_item",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="flashsalesession",
            index=models.Index(
                fields=["start_time", "end_time"], name="products_fl_start_t_dddde9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flashsalesession",
            index=models.Index(fields=["status"], name="products_fl_status_7b20c1_idx"),
        ),
        migrations.AddIndex(
            model_name="flashsaleitem",
            index=models.Index(
                fields=["session", "is_active"], name="products_fl_session_b26f14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flashsaleitem",
            index=models.Index(
                fields=["product"], name="products_fl_product_f81c66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flashsaleitem",
            unique_together={("session", "product")},
        ),
    ]
