# Generated by Django 6.0.1 on 2026-01-26 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_flashsalesession_flashsaleitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=500, verbose_name="Phụ đề"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL hình ảnh"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link đích"
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        default="Xem ngay",
                        max_length=100,
                        verbose_name="Text nút",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#16a34a", max_length=50, verbose_name="Màu nền"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#ffffff", max_length=50, verbose_name="Màu chữ"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Thứ tự"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hiển thị"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày bắt đầu"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
