# Generated by Django 6.0.1 on 2026-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="link_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Link đích"
            ),
        ),
    ]
