# Generated by Django 6.0.1 on 2026-01-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_banner_link_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MegaMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name in the menu", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL friendly slug", max_length=100, unique=True
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name (e.g. 'Pill', 'Home')",
                        max_length=50,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Direct link URL (optional)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Show with highlight style (e.g. checkmark)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated category for sub-menu items",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mega Menu Item",
                "verbose_name_plural": "Mega Menu Items",
                "ordering": ["order"],
            },
        ),
    ]
