# Generated by Django 6.0.1 on 2026-01-27 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_megamenuitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MegaMenuItem",
        ),
    ]
