# Generated by Django 6.0.1 on 2026-02-05 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g. Thuốc)', max_length=100)),
                ('code', models.CharField(help_text='Unique code (e.g. MEDICINE)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
