# Generated by Django 6.0.1 on 2026-02-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_producttype_remove_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, help_text='Type of product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype'),
        ),
    ]
