apiVersion: v1
kind: Secret
metadata:
  name: banthuoc-secrets
  namespace: banthuoc
type: Opaque
stringData:
  POSTGRES_DB: banthuoc_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDIS_PASSWORD: secure_redis_password
  DJANGO_SECRET_KEY: change_me_in_production
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  EMAIL_HOST_USER: hovietanh147@gmail.com
  EMAIL_HOST_PASSWORD: prhs fmfz hduc ffjp
  DEFAULT_FROM_EMAIL: hovietanh147@gmail.com
