apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: banthuoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: andyanh174/banthuoc-backend:latest
          command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "core.wsgi:application"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: banthuoc-config
            - secretRef:
                name: banthuoc-secrets
          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: banthuoc
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
