/**
 * Admin API Endpoints
 *
 * Users, Products, Categories, Manufacturers, Vouchers,
 * Flash Sales, Returns, Audit, Bug Reports, Product Types.
 *
 * Source: server/apps/users/views/admin.py, products/views/product.py,
 *         products/views/category.py, products/views/manufacturer.py,
 *         vouchers/views.py, products/views/flash_sale_admin.py,
 *         orders/views_return.py, audit/views.py, bugreport/views.py,
 *         products/views/product_type.py
 */
import type { ApiEndpoint } from "../openapi.js";

export const endpoints: ApiEndpoint[] = [
  // ── Admin Users ─────────────────────────────────────────
  {
    path: "/api/admin/users",
    method: "GET",
    summary: "Admin — List users with search (name/email/phone), status/role filter",
    tags: ["Admin", "Users"],
    auth: ["Bearer JWT (Admin)"],
    params: [
      { name: "status", in: "query", type: "string", required: false, description: "PENDING, ACTIVE, REJECTED, LOCKED" },
      { name: "role", in: "query", type: "string", required: false, description: "ADMIN, CUSTOMER" },
      { name: "search", in: "query", type: "string", required: false, description: "Search by name, email, phone" },
    ],
    response: {
      count: 100,
      results: [{ id: 1, full_name: "A", email: "a@email.com", phone: "090...", role: "CUSTOMER", status: "ACTIVE", is_verified: true, date_joined: "..." }],
    },
  },
  {
    path: "/api/admin/users/create",
    method: "POST",
    summary: "Admin — Create user (no password validation for admin)",
    tags: ["Admin", "Users"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: {
      full_name: "string", email: "string (optional)", phone: "string (required)",
      password: "string (no password policy enforced)", password_confirm: "string",
      role: "ADMIN | CUSTOMER", status: "PENDING | ACTIVE",
    },
    response: { id: 2, full_name: "B", email: null, phone: "091...", role: "CUSTOMER", status: "ACTIVE" },
  },
  {
    path: "/api/admin/users/{id}",
    method: "GET",
    summary: "Admin — Get user detail with business profile, favorites, orders, point logs",
    tags: ["Admin", "Users"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "integer", required: true, description: "User ID" }],
    response: {
      id: 1, full_name: "A", email: "a@email.com", phone: "090...", role: "CUSTOMER", status: "ACTIVE",
      business_profile: { business_name: "Nha Thuoc A", license_number: "GP-001", tax_id: "...", address: "..." },
      favorites: [], orders: [], point_logs: [],
    },
  },
  {
    path: "/api/admin/users/{id}/update",
    method: "PATCH",
    summary: "Admin — Update user (partial update, any field)",
    tags: ["Admin", "Users"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "integer", required: true, description: "User ID" }],
    requestBody: { full_name: "string", email: "string", phone: "string", role: "string", status: "string", is_verified: "boolean" },
    response: { id: 1, "status": "ok" },
  },
  {
    path: "/api/admin/users/{id}/delete",
    method: "DELETE",
    summary: "Admin — Delete user",
    tags: ["Admin", "Users"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "integer", required: true, description: "User ID" }],
    response: { message: "User deleted" },
  },
  {
    path: "/api/admin/users/{id}/status",
    method: "PATCH",
    summary: "Admin — Update user status. Rejection requires a reason.",
    tags: ["Admin", "Users"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "integer", required: true, description: "User ID" }],
    requestBody: { status: "ACTIVE | LOCKED | REJECTED", reason: "string (required if REJECTED)" },
    response: { id: 1, status: "LOCKED" },
  },

  // ── Admin Products ──────────────────────────────────────
  {
    path: "/api/admin/products/",
    method: "GET",
    summary: "Admin — List all products (including inactive)",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [
      { name: "status", in: "query", type: "string", required: false, description: "ACTIVE, INACTIVE, OUT_OF_STOCK" },
      { name: "search", in: "query", type: "string", required: false, description: "Search by name" },
    ],
    response: { count: 2000, results: [{ id: "uuid", name: "...", category_name: "...", manufacturer_name: "...", status: "ACTIVE" }] },
  },
  {
    path: "/api/admin/products/",
    method: "POST",
    summary: "Admin — Create product with category/manufacturer UUIDs, images array",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: {
      name: "string", slug: "string", price: "number", sale_price: "number (optional)",
      category: "uuid", manufacturer: "uuid",
      product_type: "uuid", unit: "string", description: "string (HTML)",
      stock_quantity: "integer", requires_prescription: "boolean",
      images: "[{image_url: string, alt_text: string, is_primary: boolean, sort_order: integer}]",
    },
    response: { id: "uuid", name: "...", slug: "...", status: "ACTIVE" },
  },
  {
    path: "/api/admin/products/{id}/",
    method: "GET",
    summary: "Admin — Get product detail for editing",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "uuid", required: true, description: "Product UUID" }],
    response: { id: "uuid", name: "...", description: "...", stock_quantity: 100, images: [] },
  },
  {
    path: "/api/admin/products/{id}/",
    method: "PATCH",
    summary: "Admin — Partial update product",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "uuid", required: true, description: "Product UUID" }],
    response: { id: "uuid" },
  },
  {
    path: "/api/admin/products/{id}/",
    method: "DELETE",
    summary: "Admin — Delete product",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "uuid", required: true, description: "Product UUID" }],
    response: { message: "Product deleted" },
  },
  {
    path: "/api/admin/products/bulk-import/",
    method: "POST",
    summary: "Admin — Bulk import products from Excel/CSV file",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: { file: "File (.xlsx or .csv)" },
    response: { imported: 50, errors: [{ row: 5, error: "Missing name" }] },
  },
  {
    path: "/api/admin/products/bulk-import/template/",
    method: "GET",
    summary: "Admin — Download bulk import Excel template",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    response: { content_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", description: "Excel template file" },
  },

  // ── Admin Categories ────────────────────────────────────
  {
    path: "/api/categories/",
    method: "POST",
    summary: "Admin — Create category",
    tags: ["Admin", "Categories"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: { name: "string", slug: "string", parent_id: "uuid (optional)", image: "File (optional)", is_active: "boolean" },
    response: { id: "uuid", name: "...", slug: "...", parent: null },
  },
  {
    path: "/api/categories/{slug}/",
    method: "PUT",
    summary: "Admin — Update category",
    tags: ["Admin", "Categories"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "slug", in: "path", type: "string", required: true, description: "Category slug" }],
    response: { id: "uuid" },
  },
  {
    path: "/api/categories/{slug}/",
    method: "DELETE",
    summary: "Admin — Delete category",
    tags: ["Admin", "Categories"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "slug", in: "path", type: "string", required: true, description: "Category slug" }],
    response: { message: "Category deleted" },
  },
  {
    path: "/api/categories/{pk}/move/",
    method: "POST",
    summary: "Admin — Move category in tree (change parent)",
    tags: ["Admin", "Categories"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "pk", in: "path", type: "uuid", required: true, description: "Category UUID" }],
    requestBody: { parent_id: "uuid | null" },
    response: { id: "uuid", parent: { id: "uuid", name: "..." } },
  },

  // ── Admin Manufacturers ─────────────────────────────────
  {
    path: "/api/admin/manufacturers/",
    method: "GET",
    summary: "Admin — List manufacturers (search: name, country; order: name, created_at)",
    tags: ["Admin", "Manufacturers"],
    auth: ["Bearer JWT (Admin)"],
    params: [
      { name: "search", in: "query", type: "string", required: false, description: "Search by name or country" },
      { name: "ordering", in: "query", type: "string", required: false, description: "name, -created_at" },
    ],
    response: { count: 50, results: [{ id: "uuid", name: "Domesco", slug: "domesco", country: "Vietnam" }] },
  },
  {
    path: "/api/admin/manufacturers/",
    method: "POST",
    summary: "Admin — Create manufacturer",
    tags: ["Admin", "Manufacturers"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: { name: "string", slug: "string", country: "string", logo: "File (optional)", description: "string" },
    response: { id: "uuid", name: "...", slug: "..." },
  },
  {
    path: "/api/admin/manufacturers/{id}/",
    method: "PUT",
    summary: "Admin — Update manufacturer",
    tags: ["Admin", "Manufacturers"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "uuid", required: true, description: "Manufacturer UUID" }],
    response: { id: "uuid" },
  },
  {
    path: "/api/admin/manufacturers/{id}/",
    method: "DELETE",
    summary: "Admin — Delete manufacturer",
    tags: ["Admin", "Manufacturers"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "uuid", required: true, description: "Manufacturer UUID" }],
    response: { message: "Deleted" },
  },

  // ── Admin Vouchers ──────────────────────────────────────
  {
    path: "/api/vouchers/manage/",
    method: "GET",
    summary: "Admin — List vouchers (filter: status, search: code/name)",
    tags: ["Admin", "Vouchers"],
    auth: ["Bearer JWT (Admin)"],
    params: [
      { name: "status", in: "query", type: "string", required: false, description: "ACTIVE, EXPIRED, DISABLED" },
      { name: "search", in: "query", type: "string", required: false, description: "Search by code or name" },
    ],
    response: { count: 20, results: [{ id: "uuid", code: "SALE10", name: "...", discount_type: "PERCENTAGE", status: "ACTIVE" }] },
  },
  {
    path: "/api/vouchers/manage/",
    method: "POST",
    summary: "Admin — Create voucher",
    tags: ["Admin", "Vouchers"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: {
      code: "string", name: "string", description: "string (optional)",
      discount_type: "PERCENTAGE | FIXED", discount_value: "number",
      min_order_value: "number", max_discount: "number",
      usage_limit: "integer", max_per_user: "integer",
      start_date: "date", end_date: "date",
      applicable_categories: "[uuid]", applicable_products: "[uuid]",
    },
    response: { id: "uuid", code: "SALE20" },
  },

  // ── Admin Flash Sales ───────────────────────────────────
  {
    path: "/api/admin/flash-sales/",
    method: "GET",
    summary: "Admin — List flash sale sessions (search: name; filter: status, is_active)",
    tags: ["Admin", "Flash Sale"],
    auth: ["Bearer JWT (Admin)"],
    params: [
      { name: "status", in: "query", type: "string", required: false, description: "SCHEDULED, ACTIVE, ENDED" },
      { name: "search", in: "query", type: "string", required: false, description: "Search by name" },
    ],
    response: { count: 5, results: [{ id: "uuid", name: "Flash Sale 11/11", status: "ACTIVE", total_items_count: 25 }] },
  },
  {
    path: "/api/admin/flash-sales/",
    method: "POST",
    summary: "Admin — Create flash sale session",
    tags: ["Admin", "Flash Sale"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: { name: "string", description: "string", start_time: "datetime", end_time: "datetime", is_active: "boolean" },
    response: { id: "uuid", name: "...", status: "SCHEDULED" },
  },
  {
    path: "/api/admin/flash-sales/{id}/add_products/",
    method: "POST",
    summary: "Admin — Add products to a flash sale session",
    tags: ["Admin", "Flash Sale"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "id", in: "path", type: "uuid", required: true, description: "Session UUID" }],
    requestBody: { products: "[{product_id: uuid, flash_sale_price: number, total_quantity: integer, max_per_user: integer}]" },
    response: { added: 5, errors: [] },
  },

  // ── Admin Returns ───────────────────────────────────────
  {
    path: "/api/admin/returns/",
    method: "GET",
    summary: "Admin — List return requests (filter: status)",
    tags: ["Admin", "Returns"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "status", in: "query", type: "string", required: false, description: "PENDING_REVIEW, APPROVED, REJECTED, COMPLETED" }],
    response: { count: 10, results: [{ id: "uuid", order_id: 1, user: {}, reason: "...", status: "PENDING_REVIEW" }] },
  },
  {
    path: "/api/admin/returns/{return_id}/action/",
    method: "POST",
    summary: "Admin — Approve/reject return request",
    tags: ["Admin", "Returns"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "return_id", in: "path", type: "uuid", required: true, description: "Return request UUID" }],
    requestBody: { action: "APPROVE | REJECT", admin_note: "string (optional)" },
    response: { id: "uuid", status: "APPROVED" },
  },

  // ── Admin Audit ─────────────────────────────────────────
  {
    path: "/api/admin/audit-logs/",
    method: "GET",
    summary: "Admin — List audit logs (who did what, when)",
    tags: ["Admin", "Audit"],
    auth: ["Bearer JWT (Admin)"],
    params: [
      { name: "user_id", in: "query", type: "integer", required: false, description: "Filter by user ID" },
      { name: "action", in: "query", type: "string", required: false, description: "LOGIN, LOGOUT, CREATE_ORDER, UPDATE_PRODUCT, ..." },
    ],
    response: { count: 5000, results: [{ id: 1, user: "admin", action: "UPDATE_PRODUCT", target_type: "products.Product", target_id: "uuid", timestamp: "..." }] },
  },
  {
    path: "/api/admin/audit-logs/users/{user_id}/",
    method: "GET",
    summary: "Admin — Get audit log for specific user",
    tags: ["Admin", "Audit"],
    auth: ["Bearer JWT (Admin)"],
    params: [{ name: "user_id", in: "path", type: "integer", required: true, description: "User ID" }],
    response: [{ id: 1, action: "LOGIN", timestamp: "..." }, { id: 2, action: "CREATE_ORDER", timestamp: "..." }],
  },

  // ── Admin Product Types ─────────────────────────────────
  {
    path: "/api/admin/product-types/",
    method: "GET",
    summary: "Admin — List product types (MEDICINE, SUPPLEMENT, COSMETIC, etc.)",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin/ReadOnly)"],
    params: [
      { name: "search", in: "query", type: "string", required: false, description: "Search by name or code" },
      { name: "ordering", in: "query", type: "string", required: false, description: "name, -created_at" },
    ],
    response: [{ id: "uuid", name: "Thuốc", code: "MEDICINE" }, { id: "uuid", name: "Thực phẩm chức năng", code: "SUPPLEMENT" }],
  },
  {
    path: "/api/admin/product-types/",
    method: "POST",
    summary: "Admin — Create product type",
    tags: ["Admin", "Products"],
    auth: ["Bearer JWT (Admin)"],
    params: [],
    requestBody: { name: "string", code: "string" },
    response: { id: "uuid", name: "...", code: "..." },
  },

  // ── Bug Reports ─────────────────────────────────────────
  {
    path: "/api/admin/bug-reports/submit/",
    method: "POST",
    summary: "Submit bug report (from frontend, any authenticated user)",
    tags: ["Admin", "Bug Reports"],
    auth: ["Bearer JWT"],
    params: [],
    requestBody: { title: "string", description: "string", screenshot: "File (optional)" },
    response: { id: "uuid", title: "...", status: "OPEN" },
  },
];
