# Generated by Django 6.0.1 on 2026-01-28 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0007_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("province", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("ward", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPING", "Shipping"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("BANKING", "Banking Transfer"),
                        ],
                        default="COD",
                        max_length=20,
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("final_amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "points_awarded",
                    models.BooleanField(
                        default=False,
                        help_text="True if loyalty points have been given",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
