# Generated by Django 6.0.1 on 2026-01-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.IntegerField(
                default=0, help_text="Accumulated loyalty points"
            ),
        ),
    ]
