# Generated by Django 6.0.1 on 2026-01-30 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("users", "0003_user_loyalty_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardPointLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Points change (positive or negative)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ORDER_EARN", "Earned from Order"),
                            ("ORDER_REFUND", "Deducted from Refund"),
                            ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                            ("REDEEM", "Redeemed for Discount"),
                        ],
                        default="ORDER_EARN",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related order if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_logs",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
